import {
  ArrowLeft,
  CirclePlus,
  CircleX,
  EditIcon,
  EllipsisVertical,
  Heart,
  Home,
  Image,
  MapPin,
  MessageCircle,
  MoonStar,
  MoreHorizontal,
  Repeat2,
  Search,
  Settings,
  SmilePlus,
  User,
} from "lucide-react-native";

export const iconMapping = {
  more: MoreHorizontal,
  message: MessageCircle,
  configuration: Settings,
  "back-row": ArrowLeft,
  edit: EditIcon,
  post: CirclePlus,
  home: Home,
  profile: User,
  like: Heart,
  repeat: Repeat2,
  image: Image,
  close: CircleX,
  emoji: SmilePlus,
  location: MapPin,
  "more-vertical": EllipsisVertical,
  moon: MoonStar,
  search: Search,
};
